public class Constants {
  // Account Record
  public static final String ACCOUNT_API_NAME = 'Account';
  public static final String PFA_CUSTOMER_Account = 'PFA Customer Account';

  // Lead Record Types
  public static final String PFA_CUSTOMER_LEAD_LABEL = 'PFA Customer Lead';
  public static final String VENDOR_LEAD_LABEL = 'Vendor Lead';
  public static final String CUSTOMER_LEAD_LABEL = 'Customer Lead';

  // Opportunity Constants
  public static final String OPPORTUNITY_API_NAME = 'Opportunity';
  public static final String DEFAULT_OPPORTUNITY = 'Default Opportunity';
  public static final String PFA_CUSTOMER_OPPORTUNITY = 'PFA Customer Opportunity';

  // Lead Status API Names
  public static final String RERIEVE_ACCOUNT_INFO_STATUS = 'Retrieve Account Info';
  public static final String NEW_STATUS = 'New';

  // Opportunity Stages
  public static final String PREPARE_SOW_STAGE = 'Prepare SOW';

  //Product2 Constants
  public static final String PRODUCT2_API_NAME = 'Product2';
  public static final String PFA_PRODUCT = 'PFA Product';

  // ExpensesMiscellaneous Constants
  public static final String EXP_TYPE_1 = 'Materials & Samples Purchase';
  public static final String EXP_TYPE_2 = 'Storage';
  public static final String EXP_TYPE_3 = 'PFA Handling Fees';
  public static final String EXP_TYPE_4 = 'Shipping/Postage + Handling';
  public static final String EXP_TYPE_5 = 'Scheduling & Reporting Software';
}
