/*
 * Description: This class is for all constant variables
 * Author: Imran
 * Created Date: 27th July 2023
 * Version:1.0.0 - Imran - 27th July 2023
 */
public with sharing class ConstantUtility {
  public static final String CUSTOMER_ACCOUNT = 'Customer Account';
  public static final String VENDOR_ACCOUNT = 'Vendor Account';
  public static final String PFA_CUSTOMER_ACCOUNT = 'PFA Customer Account';
}
