public class QuicbooksConfiguration {
  public String accessToken { get; set; }
  public String realMId { get; set; }
  public String refreshToken { get; set; }
  public String syncedAccountTittle { get; set; }
  public String qbCredentialsId { get; set; }

  public String qbCustomField { get; set; }
  public String qbCustomFieldId { get; set; }
  public String qbAccessTokeEndPoint { get; set; }
  public String qbApiEndPoint { get; set; }
  public String qbAuthorizationEndPoint { get; set; }
  public String qbAuthorizationScope { get; set; }
  public String qbClientId { get; set; }
  public String qbClientSecret { get; set; }
  public String qbId { get; set; }
  public String qbRedirectURI { get; set; }
  public String qbTimeZone { get; set; }
  public String quickbooksAccountTittle { get; set; }

  public String breakdownServiceId { get; set; }
  public String brokerageServiceId { get; set; }
  public String dutyServiceId { get; set; }
  public String fixedChargesServiceId { get; set; }
  public String inboundServiceId { get; set; }
  public String runChargeServiceId { get; set; }
  public String decorationServiceId { get; set; }
  public String fulfillmentServiceId { get; set; }
}
