@isTest
public class Test_artworkResults {
  @isTest
  public static void testfunction() {
    artworkResults test = new artworkResults();
    test.logoColor = 'test';
    test.counter = 1;
    test.imprintType = '';
    test.logoSize = '';
    test.opportunityLineItem = '';
    test.proofRequired = '';
    test.repeatLogo = '';
    test.supplierNotes = '';
    test.documentId = '';
    test.logoName = '';
    test.id = '';
  }
}
