@isTest
public class Test_ScriptClass {
  // @isTest
  // public static void coverCode(){
  //     Test.setMock(HttpCalloutMock.Class, new MockTestResponse());
  //     QB_Credentials__c qbc = new QB_Credentials__c();
  //     qbc.Access_token__c = 'akjdkjnakcnhjsvavkgdvsaytsevfuysabldlciublsdiuabiudlbfsadf';
  //     qbc.Refresh_token__c = 'ajsndkjbakhucbuydasiycbyuasic';
  //     qbc.RealMId__c = '5165118946516321';
  //     insert qbc;
  //     Test.startTest();
  //     ScriptClass.getOrders();
  //     Test.stopTest();
  // }

  // @isTest
  // public static void coverCodeGetDate(){
  //     ScriptClass.getDateFromString('2019-09-17');
  // }
}
