name: TEST

# Definition when the workflow should run
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# Workflow environment variables
env:
  DEVHUB_SFDX_CLIENT_ID: ${{ secrets.DEVHUB_SFDX_CLIENT_ID }}
  DEVHUB_SFDX_JWT_SERVER_KEY: ${{ secrets.DEVHUB_SFDX_JWT_SERVER_KEY }}
  DEVHUB_SFDX_JWT_SERVER_KEY1: ${{ secrets.DEVHUB_SFDX_JWT_SERVER_KEY1}}
  DEVHUB_SFDX_JWT_USERNAME: ${{ secrets.DEVHUB_SFDX_JWT_USERNAME }}
  DEVHUB_SFDX_JWT_INSTANCE_URL: ${{ secrets.DEVHUB_SFDX_JWT_INSTANCE_URL }}
  DEVHUB_SFDX_JWT_ALIAS: ${{ secrets.DEVHUB_SFDX_JWT_ALIAS }}

# Jobs to be executed
jobs:
  # Formatting and linting only runs on human-submitted PRs
  format-lint-lwc-tests:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: "Install Salesforce CLI"
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version
      - name: "Authenticate Dev Hub via JWT"
        env:
          SECRET: ${{env.DEVHUB_SFDX_JWT_SERVER_KEY1}}
        run: |
          echo $SECRET >> $HOME/server.key
          sudo chmod 600 $HOME/server.key
          sf org login jwt --client-id ${{ env.DEVHUB_SFDX_CLIENT_ID }} --jwt-key-file $HOME/server.key --username ${{ env.DEVHUB_SFDX_JWT_USERNAME }} --instance-url ${{ env.DEVHUB_SFDX_JWT_INSTANCE_URL }} --alias ${{ env.DEVHUB_SFDX_JWT_ALIAS }}
